// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxEhNZ4QXzt3M-3XL9lvOxb2Soylg-1Q',
    appId: '1:128606098808:web:fea9a30d90dadfab14a48d',
    messagingSenderId: '128606098808',
    projectId: 'chat-46f2f',
    authDomain: 'chat-46f2f.firebaseapp.com',
    storageBucket: 'chat-46f2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNS1-VFL81HGQ0P9AsM2YpCWmL8G0-iLo',
    appId: '1:128606098808:android:8674fdfcee187e3714a48d',
    messagingSenderId: '128606098808',
    projectId: 'chat-46f2f',
    storageBucket: 'chat-46f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAon1h8RLjurP7slVJRkzXUxDXeiObG8fs',
    appId: '1:128606098808:ios:1af6e6b5e8ec1e3614a48d',
    messagingSenderId: '128606098808',
    projectId: 'chat-46f2f',
    storageBucket: 'chat-46f2f.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAon1h8RLjurP7slVJRkzXUxDXeiObG8fs',
    appId: '1:128606098808:ios:1af6e6b5e8ec1e3614a48d',
    messagingSenderId: '128606098808',
    projectId: 'chat-46f2f',
    storageBucket: 'chat-46f2f.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuxEhNZ4QXzt3M-3XL9lvOxb2Soylg-1Q',
    appId: '1:128606098808:web:acae17b112e3cca414a48d',
    messagingSenderId: '128606098808',
    projectId: 'chat-46f2f',
    authDomain: 'chat-46f2f.firebaseapp.com',
    storageBucket: 'chat-46f2f.firebasestorage.app',
  );
}
